spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.feesmpizmwcotvtehecs
spring.datasource.password=kel1pbojuara
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.keepalive-time=15000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

gemini.api.key=AQ.Ab8RN6IElPepWIHDHu0K5tL866pSD8n3IGCmt5BGYuxZc2QvDQ
server.port=8081

# Konfigurasi Keamanan JWT
jwt.secret=pbokelompok1juaraantimbgprabowogibran
jwt.expiration=86400000

# Konfigurasi Upload File (dokumen task PDF/TXT)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB
spring.servlet.multipart.file-size-threshold=2KB
app.upload.dir=uploads/tasks

# =============================
# BREVO SMTP
# =============================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=heyjiproo@gmail.com
app.mail.frontend-url=http://localhost:5173

# Ambang batas notifikasi (dalam jam sebelum deadline)
app.notification.deadline-reminder-hours=24

# =============================
# FONNTE
# =============================
fonnte.token=kvwFt3do4CjZdS8m8j4j