spring.application.name=backend

# ===============================
# KONFIGURASI DATABASE SUPABASE
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.feesmpizmwcotvtehecs
spring.datasource.password=kel1pbojuara
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# KONFIGURASI JPA / HIBERNATE
# ===============================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true